### ISSUE TITLE
Python import error

### ISSUE THREAD

**Issue by pl52feve** [jianboqi/CSF#46]
Hi, I tried to install CSF on WSL. It seemed that the install worked, however when importing the library in my code, this error occurs:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/my_name/conda/lib/python3.9/site-packages/CSF-1.1.1-py3.9-linux-x86_64.egg/CSF.py", line 17, in <module>
    _CSF = swig_import_helper()
  File "/home/my_name/conda/lib/python3.9/site-packages/CSF-1.1.1-py3.9-linux-x86_64.egg/CSF.py", line 16, in swig_import_helper
    return importlib.import_module('_CSF')
  File "/home/my_name/conda/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/my_name/conda/lib/python3.9/site-packages/CSF-1.1.1-py3.9-linux-x86_64.egg/_CSF.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv

Do you have an idea what could be wrong? Thanks so much in advance.

**Comment by jianboqi** [comment]
It may be related to the versionof the gcc compiler you have used, maybe because of missmatch in c-compiler and cxx-compiler version of anaconda and system. I never tested the WSL.
