### ISSUE TITLE
numpy 2.0+ compatibility

### ISSUE THREAD

**Issue by dvolgyes** [jianboqi/CSF#59]
Hi,

It is a great package, and it would be most helpful if you could rebuild it for numpy 2.0 support.
Currently importing leads to this error message (slightly edited):
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/....py", line 6, in <module>
    import CSF
  File "/home/.../site-packages/CSF.py", line 15, in <module>
    import _CSF
Traceback (most recent call last):
  File "/home/.../site-packages/numpy/core/_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
```

Very likely the only thing you would need to do is compile the code with Numpy 2.0 (and publish it on pypi :) ),
that suppose to be backward compatible. (But I don't completely follow the array magic inside
CSF codes, so maybe there is more.)
https://numpy.org/doc/stable/dev/depending_on_numpy.html#numpy-2-abi-handling

Thanks!

**Comment by JohnHagood** [comment]
If you would like to do this locally, make the following changes to pyproject.toml:

`[build-system]
requires = ["wheel","setuptools", "numpy>=2.0.0rc1"]
dependencies = ["oldest-supported-numpy"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp3{8,9,10,11,12}-*" `

run python setup.py bdist_wheel (make sure you have installed setuptools wheel -- pip install setuptools wheel)

you can then run pip install dist/<generated wheel dist>

**Comment by jianboqi** [comment]
Thanks for your advice and help, I have rebuild the CSF for numpy 2.0 support. You can use `pip install cloth-simulation-filter` to install new CSF version.
